FROM eclipse-temurin:21-jdk

# 作業ディレクトリ設定
WORKDIR /app

# JARファイルをコピー
COPY target/mentalapp-0.0.1-SNAPSHOT.jar app.jar

# 環境変数設定
ENV PORT=8080
ENV SPRING_PROFILES_ACTIVE=ecs

EXPOSE 8080

# ECSエントリーポイント設定
ENTRYPOINT ["java", "-jar", "app.jar"]