NegativeFeel.create(negative_feel_name: '不安')
NegativeFeel.create(negative_feel_name: '苦しい')
NegativeFeel.create(negative_feel_name: '心配')
NegativeFeel.create(negative_feel_name: '憂うつ')
NegativeFeel.create(negative_feel_name: '不快感')
NegativeFeel.create(negative_feel_name: '嫌悪')
NegativeFeel.create(negative_feel_name: '恥ずかしい')
NegativeFeel.create(negative_feel_name: '怒り')
NegativeFeel.create(negative_feel_name: '悲しい')
NegativeFeel.create(negative_feel_name: '落ち込む')
NegativeFeel.create(negative_feel_name: '怖い')
NegativeFeel.create(negative_feel_name: '動揺')
NegativeFeel.create(negative_feel_name: '疲れている')
NegativeFeel.create(negative_feel_name: '罪悪感')

PositiveFeel.create(positive_feel_name: '愛されている')
PositiveFeel.create(positive_feel_name: '熱心')
PositiveFeel.create(positive_feel_name: '自由')
PositiveFeel.create(positive_feel_name: '喜び')
PositiveFeel.create(positive_feel_name: '落ち着き')
PositiveFeel.create(positive_feel_name: '充足感')
PositiveFeel.create(positive_feel_name: '好奇心')
PositiveFeel.create(positive_feel_name: '高揚感')
PositiveFeel.create(positive_feel_name: '自信')
PositiveFeel.create(positive_feel_name: 'ホッとする')
PositiveFeel.create(positive_feel_name: 'やる気')
PositiveFeel.create(positive_feel_name: '感謝')
PositiveFeel.create(positive_feel_name: '思いやり')
PositiveFeel.create(positive_feel_name: '感心')

DistortionList.create(distortion_name: '白黒思考', info: '「完璧にやろうとしていない？」')
DistortionList.create(distortion_name: '過度な一般化', info: '「一度の失敗で、また同じ事が起こると思っていない？」') 
DistortionList.create(distortion_name: '心のフィルター', info: '「悪い点だけ目についていない？」') 
DistortionList.create(distortion_name: 'マイナス化思考', info: '「自分を素直に褒めることができない？」' )
DistortionList.create(distortion_name: '読心術', info: '「相手のことを思い込んでいない？」' )
DistortionList.create(distortion_name: '運命の先読み', info: '「私は一生不幸だ、と思いすぎていない？」') 
DistortionList.create(distortion_name: '破滅化', info: '「すこしの失敗を大げさにとらえすぎていない？」' )
DistortionList.create(distortion_name: '感情的決めつけ', info: '「感情に巻き込まれていない？」' )
DistortionList.create(distortion_name: 'べき思考', info: '「自分や相手に厳しすぎない？」' )
DistortionList.create(distortion_name: 'レッテル貼り', info: '「私はこういう人間だ、と思いすぎていない？」') 
DistortionList.create(distortion_name: '内なる批評家', info: '「自分を責めすぎていない？」' )
DistortionList.create(distortion_name: '他人批判', info: '「あいつのせい、って思いすぎていない？」')